# Basic Site Settings
locale: "en-US"
title: "Your Name / CV Title"
description: "A brief description of your professional background."
url: "https://yourusername.github.io" # Replace with your GitHub Pages URL
baseurl: "" # No subpath

# Author Information
author:
  name: "Your Name"
  bio: "A short biography about yourself."
  email: "your.email@example.com"
  location: "Your Location"
  github: "yourusername" # Your GitHub username
  linkedin: "your-linkedin-profile" # Your LinkedIn profile URL
  twitter: "your-twitter-handle" # Your Twitter handle

# Publication Categories
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'
  conferences:
    title: 'Conference Papers'

# Site Settings
comments:
  provider: false # Disable comments
read_more: "disabled" # Disable "Read more" links

# SEO Related
google_site_verification: ""
bing_site_verification: ""

# Analytics
analytics:
  provider: "false" # Disable analytics

# Markdown Processing
markdown: kramdown

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Outputting
permalink: /:title/ # Simple permalink structure
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude unnecessary files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .git
  - .github
  - README.md
  - LICENSE

# HTML Compression
compress_html:
  clippings: all
